/**
 * Permission keys and role → permission matrices.
 */

import { USER_ROLES, type UserRoleType } from './roles';

export const USER_PERMISSIONS = {
  CREATE_USER: 'create_user',
  READ_USER: 'read_user',
  UPDATE_USER: 'update_user',
  DELETE_USER: 'delete_user',
  MANAGE_SYSTEM: 'manage_system',
  VIEW_DASHBOARD: 'view_dashboard',
  MANAGE_OWN_PROFILE: 'manage_own_profile',
} as const;

export type PermissionType = (typeof USER_PERMISSIONS)[keyof typeof USER_PERMISSIONS];

const MANAGER_USER_PERMISSIONS: readonly PermissionType[] = [
  USER_PERMISSIONS.CREATE_USER,
  USER_PERMISSIONS.READ_USER,
  USER_PERMISSIONS.UPDATE_USER,
  USER_PERMISSIONS.VIEW_DASHBOARD,
  USER_PERMISSIONS.MANAGE_OWN_PROFILE,
] as const;

export const ROLE_PERMISSIONS: Record<UserRoleType, readonly PermissionType[]> = {
  [USER_ROLES.ADMIN]: [
    USER_PERMISSIONS.CREATE_USER,
    USER_PERMISSIONS.READ_USER,
    USER_PERMISSIONS.UPDATE_USER,
    USER_PERMISSIONS.DELETE_USER,
    USER_PERMISSIONS.MANAGE_SYSTEM,
    USER_PERMISSIONS.VIEW_DASHBOARD,
    USER_PERMISSIONS.MANAGE_OWN_PROFILE,
  ],
  [USER_ROLES.ACCOUNTANT]: [
    USER_PERMISSIONS.CREATE_USER,
    USER_PERMISSIONS.READ_USER,
    USER_PERMISSIONS.UPDATE_USER,
    USER_PERMISSIONS.DELETE_USER,
    USER_PERMISSIONS.VIEW_DASHBOARD,
    USER_PERMISSIONS.MANAGE_OWN_PROFILE,
  ],
  [USER_ROLES.ACCOUNT_MANAGER]: MANAGER_USER_PERMISSIONS,
  [USER_ROLES.TECH_MANAGER]: MANAGER_USER_PERMISSIONS,
  [USER_ROLES.AGENT_MANAGER]: MANAGER_USER_PERMISSIONS,
  [USER_ROLES.TECH]: [
    USER_PERMISSIONS.VIEW_DASHBOARD,
    USER_PERMISSIONS.MANAGE_OWN_PROFILE,
  ],
  [USER_ROLES.AGENT]: [
    USER_PERMISSIONS.VIEW_DASHBOARD,
    USER_PERMISSIONS.MANAGE_OWN_PROFILE,
  ],
};

/** Which roles each role may create (matches backend). */
export const ROLE_CREATION_PERMISSIONS: Record<UserRoleType, readonly UserRoleType[]> = {
  [USER_ROLES.ADMIN]: [
    USER_ROLES.ADMIN,
    USER_ROLES.ACCOUNTANT,
    USER_ROLES.ACCOUNT_MANAGER,
    USER_ROLES.TECH_MANAGER,
    USER_ROLES.AGENT_MANAGER,
    USER_ROLES.TECH,
    USER_ROLES.AGENT,
  ],
  [USER_ROLES.ACCOUNTANT]: [USER_ROLES.TECH],
  [USER_ROLES.ACCOUNT_MANAGER]: [USER_ROLES.ACCOUNTANT],
  [USER_ROLES.TECH_MANAGER]: [USER_ROLES.TECH],
  [USER_ROLES.AGENT_MANAGER]: [USER_ROLES.AGENT],
  [USER_ROLES.TECH]: [],
  [USER_ROLES.AGENT]: [],
};
